### ISSUE TITLE
Docs -> Sphinx

### ISSUE THREAD

**Issue by kejbaly2** [psss/status-report#10]
@psss 

Ultimately, while it's not perfect, I think it's going to be better if we have a readme file and man file that are separate from each other.

In 0.4 I've made a static cut of the man page; i don't think the man page will need to be updated very often. And once we have full docs... man page is just one more file out of many that we're going to need to make sure is accurate each time. It should be as simple as possible anyway, so hopefully even it won't need to be updated. In 0.4 the man pages are produced now using sphinx. The RPM makefile has been updated to build using sphinx. HTML output of the documentation is also using sphinx and is automatically regenerated over at status-report.readthedocs.org after each commit (you'll need to enable that in github repo hooks). Until you enable that hook i'm just manually re-generating the docs after commits though with a simple curl command::

    curl -X POST http://readthedocs.org/build/status-report

See for example:
http://status-report.readthedocs.org/en/0.4/overview.html

See https://github.com/psss/status-report/commit/7647e8232223abcf8651a08fbeb6ffb0cc28ce09

I've added git commit hooks too so now stuff can be checked automatically prior to making the commit. You need to enable it to work though:

    # UPDATE according to your actual abs_path to this repo
    PATH = ~/status-report/git-hooks
    ln -s $(PATH)/pre-commit.py .git/hooks/pre-commit
    ln -s $(PATH)/commit-msg.py .git/hooks/commit-msg

Currently enabled are commit-msg check (<= 50c) and pre-commit checks (RPM build and py.test)

**Comment by kejbaly2** [comment]
http://status-report.readthedocs.org/en/0.4/index.html

**Comment by kejbaly2** [comment]
To enable ReadTheDocs automatic building of docs on active branches; select settings for your project (not for your account) in the navigation panel on the right-hand side choose Webhooks & Services. Enable ReadTheDocs under Add Service dropdown

**Comment by psss** [comment]
Thanks for the great introduction to Sphinx, Chris! I've merged
your documentation changes in 300ae79 and did a couple of
adjustments in 8624748. I've also enabled automated builds on Read
the Docs, however there seems to be some problem with kerberos:
https://readthedocs.org/projects/status-report/builds/3288914/
